import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import classNames from 'classnames';
import CountryTile from '../../components/CountryTile/CountryTile';
import { useGetCountries } from '../../hooks/queries/useGetCountries';
import Header from '../../components/Header/Header';

const Country: NextPage = () => {
  const router = useRouter();
  const { name } = router.query;

  const [darkMode, setDarkMode] = useState<boolean>(
    typeof window !== 'undefined' &&
      window.localStorage.getItem('darkMode') === 'true'
  );

  const { data: countries, error } = useGetCountries(name as string);

  return (
    <div className={classNames(darkMode ? 'dark' : '', 'font-nunito')}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header updateDarkMode={setDarkMode} />

      <main className="bg-very-light-gray text-very-dark-blue dark:bg-midnight-blue dark:text-white">
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-16 px-14 py-12">
          {error ? (
            <div>Error fetching data...</div>
          ) : countries?.length ? (
            countries?.map((country: any) => (
              <CountryTile key={country.name} country={country} />
            ))
          ) : (
            <div>Fetching data...</div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Country;
