import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import classNames from "classnames";
import { HiMoon } from "react-icons/hi";
import CountryTile from "../components/CountryTile/CountryTile";

const Countries: NextPage = () => {
  const [darkMode, setDarkMode] = useState<boolean>(true);

  return (
    <div className={classNames(darkMode ? "dark" : "", "font-nunito")}>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header
        className={classNames(
          "bg-white text-very-dark-blue dark:bg-dark-blue dark:text-white"
        )}
      >
        <h4 className="px-14 py-4 font-semibold inline-block">
          Where in the world?
        </h4>
        <button
          className="px-14 py-4 inline-block float-right"
          onClick={() => setDarkMode((darkMode) => !darkMode)}
        >
          <HiMoon className="inline-block mr-2 mt-1 align-top" />
          Dark Mode
        </button>
      </header>

      <main className="bg-very-light-gray text-very-dark-blue dark:bg-midnight-blue dark:text-white">
        <div className="grid grid-cols-4 gap-12">
          <CountryTile />
          <CountryTile />
          <CountryTile />
          <CountryTile />
          <CountryTile />
          <CountryTile />
        </div>
      </main>
    </div>
  );
};

export default Countries;
