import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import classNames from "classnames";
import { HiMoon } from "react-icons/hi";
import CountryTile from "../components/CountryTile/CountryTile";
import { useGetCountries } from "../hooks/queries/useGetCountries";

const Countries: NextPage = () => {
  const [darkMode, setDarkMode] = useState<boolean>(true);

  const { data: countries, error } = useGetCountries();

  return (
    <div className={classNames(darkMode ? "dark" : "", "font-nunito")}>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header
        className={classNames(
          "bg-white text-very-dark-blue dark:bg-dark-blue dark:text-white"
        )}
      >
        <h1 className="px-14 py-4 font-semibold text-xl inline-block">
          Where in the world?
        </h1>
        <button
          className="px-14 py-4 inline-block float-right"
          onClick={() => setDarkMode((darkMode) => !darkMode)}
        >
          <HiMoon className="inline-block mr-2 mt-1 align-top" />
          <span className="text-sm">Dark Mode</span>
        </button>
      </header>

      <main className="bg-very-light-gray text-very-dark-blue dark:bg-midnight-blue dark:text-white">
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-16 px-14 py-8">
          {error ? (
            <div>Error fetching data...</div>
          ) : countries?.length ? (
            countries?.map((country: any) => (
              <CountryTile key={country.name} country={country} />
            ))
          ) : (
            <div>Fetching data...</div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Countries;
